import { Event } from '@/server/db/schema';

export const ibzimEvents: Event[] = [
  {
    id: '101',
    approved: true,
    approvalExpiry: null,
    title: 'Company Awards PCAZ',
    startDate: new Date('2025-01-01T00:00:00Z'),
    endDate: new Date('2025-01-01T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'ibzim',
    locationType: 'virtual',
    type: null,
    description: 'The first day of the year, celebrated as a public holiday.',
    location: null,
    locationLink: null,
    priority: 'high',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
];

export const holidayEvents: Event[] = [
  {
    id: '001',
    approved: true,
    approvalExpiry: null,
    title: "New Year's Day",
    startDate: new Date('2025-01-01T00:00:00Z'),
    endDate: new Date('2025-01-01T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description: 'The first day of the year, celebrated as a public holiday.',
    location: null,
    locationLink: null,
    priority: 'high',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '002',
    approved: true,
    approvalExpiry: null,
    title: 'Robert Gabriel Mugabe National Youth Day',
    startDate: new Date('2025-02-21T00:00:00Z'),
    endDate: new Date('2025-02-21T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description: 'A day to celebrate and honor the youth of Zimbabwe.',
    location: null,
    locationLink: null,
    priority: 'medium',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '003',
    approved: true,
    approvalExpiry: null,
    title: 'Good Friday',
    startDate: new Date('2025-04-18T00:00:00Z'),
    endDate: new Date('2025-04-18T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description:
      'Christian holiday commemorating the crucifixion of Jesus Christ.',
    location: null,
    locationLink: null,
    priority: 'high',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '004',
    approved: true,
    approvalExpiry: null,
    title: 'Easter Saturday',
    startDate: new Date('2025-04-19T00:00:00Z'),
    endDate: new Date('2025-04-19T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description: 'The day before Easter Sunday, observed as a public holiday.',
    location: null,
    locationLink: null,
    priority: 'medium',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '005',
    approved: true,
    approvalExpiry: null,
    title: 'Easter Monday',
    startDate: new Date('2025-04-21T00:00:00Z'),
    endDate: new Date('2025-04-21T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description: 'The day after Easter Sunday, celebrated as a public holiday.',
    location: null,
    locationLink: null,
    priority: 'medium',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '006',
    approved: true,
    approvalExpiry: null,
    title: 'Independence Day',
    startDate: new Date('2025-04-18T00:00:00Z'),
    endDate: new Date('2025-04-18T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description:
      "Commemorates Zimbabwe's independence from British colonial rule in 1980.",
    location: null,
    locationLink: null,
    priority: 'high',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '007',
    approved: true,
    approvalExpiry: null,
    title: 'Workers Day',
    startDate: new Date('2025-05-01T00:00:00Z'),
    endDate: new Date('2025-05-01T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description: 'A public holiday to celebrate the contributions of workers.',
    location: null,
    locationLink: null,
    priority: 'medium',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '008',
    approved: true,
    approvalExpiry: null,
    title: 'Africa Day',
    startDate: new Date('2025-05-25T00:00:00Z'),
    endDate: new Date('2025-05-25T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description:
      'Celebrates African unity and commemorates the founding of the Organization of African Unity.',
    location: null,
    locationLink: null,
    priority: 'medium',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '009',
    approved: true,
    approvalExpiry: null,
    title: 'Heroes Day',
    startDate: new Date('2025-08-11T00:00:00Z'),
    endDate: new Date('2025-08-11T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description:
      "Honors those who died in the liberation struggle for Zimbabwe's independence.",
    location: null,
    locationLink: null,
    priority: 'high',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '010',
    approved: true,
    approvalExpiry: null,
    title: 'Defence Forces Day',
    startDate: new Date('2025-08-12T00:00:00Z'),
    endDate: new Date('2025-08-12T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description: 'Celebrates and honors the Zimbabwe Defence Forces.',
    location: null,
    locationLink: null,
    priority: 'medium',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '011',
    approved: true,
    approvalExpiry: null,
    title: 'Unity Day',
    startDate: new Date('2025-12-22T00:00:00Z'),
    endDate: new Date('2025-12-22T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description:
      'Commemorates the Unity Accord signed between ZANU-PF and PF-ZAPU in 1987.',
    location: null,
    locationLink: null,
    priority: 'medium',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '012',
    approved: true,
    approvalExpiry: null,
    title: 'Christmas Day',
    startDate: new Date('2025-12-25T00:00:00Z'),
    endDate: new Date('2025-12-25T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description: 'Christian holiday celebrating the birth of Jesus Christ.',
    location: null,
    locationLink: null,
    priority: 'high',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
  {
    id: '013',
    approved: true,
    approvalExpiry: null,
    title: 'Boxing Day',
    startDate: new Date('2025-12-26T00:00:00Z'),
    endDate: new Date('2025-12-26T00:00:00Z'),
    startTime: null,
    endTime: null,
    category: 'public',
    locationType: null,
    type: null,
    description:
      'The day after Christmas, traditionally a day for giving gifts to service workers.',
    location: null,
    locationLink: null,
    priority: 'medium',
    eventOrganizerId: null,
    recurrence: 'yearly',
    pricingTiers: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    pricingDetails: null,
    ticketsLink: null,
  },
];

export const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const daysOfWeek = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
