export const songIds = [
  'aae44935-a3ed-4969-9120-197c141abea4',
  '80faffa3-8d5b-4443-b210-389e3def6582',
  '4770e3cb-a298-4d4a-9a5c-6200e6d9011e',
  '0ea6b9dc-3062-43c3-bbc5-7a24cbf2601b',
  '1844d54e-3b6f-4f7b-8b16-a54f1da31b8a',
  '64db308f-2270-498e-9fc6-5ba668c35c45',
  '7def473a-1d86-4bcd-b575-77d8aebd705d',
  '3c4bb8fc-48a4-4df8-831a-df02ccba6173',
  '10c1a75b-d03b-4088-ab1d-5c0a993f0212',
  '6cc74932-dd6b-4f70-849c-8de10334f579',
  'a7e6f3fe-2308-4d32-8901-f70bc11b19c1',
  '6bfb12ba-876a-4264-98b4-e07b18723998',
];

export const artistProfileIds = [
  'febce1a7-1c0c-4dc8-9b89-f6112da2b5b9',
  'ea0a414b-1527-4f34-9994-f1c1c8bbda54',
  '6812ebc5-fa67-45f2-8f37-38184a9b9715',
  '1c34bbd4-a871-4717-97f1-264b7d1c2fb6',
  'b6e41a92-6f87-44f9-af0d-9bf80bcb9f8e',
  '42da1184-c749-4483-aaad-dd6607786666',
  'a2b348df-3378-4853-9ad7-7eb978787dae',
  '751e2248-761e-4bc4-a1bf-2664b7f33d35',
  '296ad13c-391a-4a53-8951-70b85b300d0b',
  '7abc5d20-fadf-4591-98a5-aef1757236e5',
  'f156939a-b8d7-46a9-a704-4bc7554b669d',
  'e4d72b66-f663-421c-a69a-2950a28adf90',
];

export const nomineeIds = [
  'nominee-001-alpha',
  'nominee-002-beta',
  'nominee-003-gamma',
  'nominee-004-delta',
  'nominee-005-eps',
  'nominee-006-zeta',
  'nominee-007-eta',
  'nominee-008-theta',
  'nominee-009-iota',
  'nominee-010-kappa',
];

export const titleIds = [
  'title-001-artist',
  'title-002-song',
  'title-003-album',
  'title-004-newcomer',
  'title-005-fanfav',
  'title-006-producer',
  'title-007-collab',
  'title-008-viral',
  'title-009-live',
  'title-010-legend',
];

export const categoryIds = [
  'cat-001-pop',
  'cat-002-rock',
  'cat-003-hiphop',
  'cat-004-rnb',
  'cat-005-indie',
  'cat-006-electronic',
  'cat-007-country',
  'cat-008-latin',
  'cat-009-kpop',
  'cat-010-jazz',
];

export function getDemoData() {
  return {
    users: [
      // Original 5 users
      {
        firstName: 'Alice',
        lastName: 'Smith',
        username: 'demo_alice1',
        email: 'demo-demo_alice1@example.com',
        phoneNumber: '+15550000001',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 2,
        ip: 100,
      },
      {
        firstName: 'Bob',
        lastName: 'Johnson',
        username: 'demo_bob2',
        email: 'demo-demo_bob2@example.com',
        phoneNumber: '+15550000002',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 1,
        ip: 101,
      },
      {
        firstName: 'Charlie',
        lastName: 'Williams',
        username: 'demo_charlie3',
        email: 'demo-demo_charlie3@example.com',
        phoneNumber: '+15550000003',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 102,
      },
      {
        firstName: 'Diana',
        lastName: 'Brown',
        username: 'demo_diana4',
        email: 'demo-demo_diana4@example.com',
        phoneNumber: '+15550000004',
        emailVerified: false,
        phoneNumberVerified: false,
        accessLevel: 1,
        ip: 103,
      },
      {
        firstName: 'Eve',
        lastName: 'Jones',
        username: 'demo_eve5',
        email: 'demo-demo_eve5@example.com',
        phoneNumber: '+15550000005',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 104,
      },
      {
        firstName: 'Frank',
        lastName: 'Garcia',
        username: 'demo_frank6',
        email: 'demo-demo_frank6@example.com',
        phoneNumber: '+15550000006',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 105,
      },
      {
        firstName: 'Grace',
        lastName: 'Miller',
        username: 'demo_grace7',
        email: 'demo-demo_grace7@example.com',
        phoneNumber: '+15550000007',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 0,
        ip: 106,
      },
      {
        firstName: 'Henry',
        lastName: 'Davis',
        username: 'demo_henry8',
        email: 'demo-demo_henry8@example.com',
        phoneNumber: '+15550000008',
        emailVerified: false,
        phoneNumberVerified: true,
        accessLevel: 2,
        ip: 107,
      },
      {
        firstName: 'Ivy',
        lastName: 'Rodriguez',
        username: 'demo_ivy9',
        email: 'demo-demo_ivy9@example.com',
        phoneNumber: '+15550000009',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 108,
      },
      {
        firstName: 'Jack',
        lastName: 'Martinez',
        username: 'demo_jack10',
        email: 'demo-demo_jack10@example.com',
        phoneNumber: '+15550000010',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 109,
      },
      {
        firstName: 'Karen',
        lastName: 'Hernandez',
        username: 'demo_karen11',
        email: 'demo-demo_karen11@example.com',
        phoneNumber: '+15550000011',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 0,
        ip: 110,
      },
      {
        firstName: 'Leo',
        lastName: 'Lopez',
        username: 'demo_leo12',
        email: 'demo-demo_leo12@example.com',
        phoneNumber: '+15550000012',
        emailVerified: false,
        phoneNumberVerified: false,
        accessLevel: 1,
        ip: 111,
      },
      {
        firstName: 'Mia',
        lastName: 'Gonzalez',
        username: 'demo_mia13',
        email: 'demo-demo_mia13@example.com',
        phoneNumber: '+15550000013',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 2,
        ip: 112,
      },
      {
        firstName: 'Nathan',
        lastName: 'Wilson',
        username: 'demo_nathan14',
        email: 'demo-demo_nathan14@example.com',
        phoneNumber: '+15550000014',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 113,
      },
      {
        firstName: 'Olivia',
        lastName: 'Anderson',
        username: 'demo_olivia15',
        email: 'demo-demo_olivia15@example.com',
        phoneNumber: '+15550000015',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 1,
        ip: 114,
      },
      {
        firstName: 'Peter',
        lastName: 'Thomas',
        username: 'demo_peter16',
        email: 'demo-demo_peter16@example.com',
        phoneNumber: '+15550000016',
        emailVerified: false,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 115,
      },
      {
        firstName: 'Quinn',
        lastName: 'Taylor',
        username: 'demo_quinn17',
        email: 'demo-demo_quinn17@example.com',
        phoneNumber: '+15550000017',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 116,
      },
      {
        firstName: 'Rachel',
        lastName: 'Moore',
        username: 'demo_rachel18',
        email: 'demo-demo_rachel18@example.com',
        phoneNumber: '+15550000018',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 2,
        ip: 117,
      },
      {
        firstName: 'Sam',
        lastName: 'Jackson',
        username: 'demo_sam19',
        email: 'demo-demo_sam19@example.com',
        phoneNumber: '+15550000019',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 0,
        ip: 118,
      },
      {
        firstName: 'Tina',
        lastName: 'Martin',
        username: 'demo_tina20',
        email: 'demo-demo_tina20@example.com',
        phoneNumber: '+15550000020',
        emailVerified: false,
        phoneNumberVerified: false,
        accessLevel: 1,
        ip: 119,
      },
      {
        firstName: 'Uma',
        lastName: 'Lee',
        username: 'demo_uma21',
        email: 'demo-demo_uma21@example.com',
        phoneNumber: '+15550000021',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 120,
      },
      {
        firstName: 'Victor',
        lastName: 'Perez',
        username: 'demo_victor22',
        email: 'demo-demo_victor22@example.com',
        phoneNumber: '+15550000022',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 121,
      },
      {
        firstName: 'Wendy',
        lastName: 'Thompson',
        username: 'demo_wendy23',
        email: 'demo-demo_wendy23@example.com',
        phoneNumber: '+15550000023',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 2,
        ip: 122,
      },
      {
        firstName: 'Xavier',
        lastName: 'White',
        username: 'demo_xavier24',
        email: 'demo-demo_xavier24@example.com',
        phoneNumber: '+15550000024',
        emailVerified: false,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 123,
      },
      {
        firstName: 'Yara',
        lastName: 'Harris',
        username: 'demo_yara25',
        email: 'demo-demo_yara25@example.com',
        phoneNumber: '+15550000025',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 124,
      },
      {
        firstName: 'Zack',
        lastName: 'Sanchez',
        username: 'demo_zack26',
        email: 'demo-demo_zack26@example.com',
        phoneNumber: '+15550000026',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 125,
      },
      {
        firstName: 'Amber',
        lastName: 'Clark',
        username: 'demo_amber27',
        email: 'demo-demo_amber27@example.com',
        phoneNumber: '+15550000027',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 1,
        ip: 126,
      },
      {
        firstName: 'Brandon',
        lastName: 'Ramirez',
        username: 'demo_brandon28',
        email: 'demo-demo_brandon28@example.com',
        phoneNumber: '+15550000028',
        emailVerified: false,
        phoneNumberVerified: false,
        accessLevel: 2,
        ip: 127,
      },
      {
        firstName: 'Chloe',
        lastName: 'Lewis',
        username: 'demo_chloe29',
        email: 'demo-demo_chloe29@example.com',
        phoneNumber: '+15550000029',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 128,
      },
      {
        firstName: 'Derek',
        lastName: 'Robinson',
        username: 'demo_derek30',
        email: 'demo-demo_derek30@example.com',
        phoneNumber: '+15550000030',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 129,
      },
      {
        firstName: 'Elena',
        lastName: 'Walker',
        username: 'demo_elena31',
        email: 'demo-demo_elena31@example.com',
        phoneNumber: '+15550000031',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 0,
        ip: 130,
      },
      {
        firstName: 'Felix',
        lastName: 'Young',
        username: 'demo_felix32',
        email: 'demo-demo_felix32@example.com',
        phoneNumber: '+15550000032',
        emailVerified: false,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 131,
      },
      {
        firstName: 'Gina',
        lastName: 'Allen',
        username: 'demo_gina33',
        email: 'demo-demo_gina33@example.com',
        phoneNumber: '+15550000033',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 2,
        ip: 132,
      },
      {
        firstName: 'Hugo',
        lastName: 'King',
        username: 'demo_hugo34',
        email: 'demo-demo_hugo34@example.com',
        phoneNumber: '+15550000034',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 133,
      },
      {
        firstName: 'Iris',
        lastName: 'Wright',
        username: 'demo_iris35',
        email: 'demo-demo_iris35@example.com',
        phoneNumber: '+15550000035',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 1,
        ip: 134,
      },
      {
        firstName: 'Jake',
        lastName: 'Scott',
        username: 'demo_jake36',
        email: 'demo-demo_jake36@example.com',
        phoneNumber: '+15550000036',
        emailVerified: false,
        phoneNumberVerified: false,
        accessLevel: 0,
        ip: 135,
      },
      {
        firstName: 'Kira',
        lastName: 'Torres',
        username: 'demo_kira37',
        email: 'demo-demo_kira37@example.com',
        phoneNumber: '+15550000037',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 136,
      },
      {
        firstName: 'Liam',
        lastName: 'Nguyen',
        username: 'demo_liam38',
        email: 'demo-demo_liam38@example.com',
        phoneNumber: '+15550000038',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 2,
        ip: 137,
      },
      {
        firstName: 'Maya',
        lastName: 'Hill',
        username: 'demo_maya39',
        email: 'demo-demo_maya39@example.com',
        phoneNumber: '+15550000039',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 0,
        ip: 138,
      },
      {
        firstName: 'Noah',
        lastName: 'Flores',
        username: 'demo_noah40',
        email: 'demo-demo_noah40@example.com',
        phoneNumber: '+15550000040',
        emailVerified: false,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 139,
      },
      {
        firstName: 'Paige',
        lastName: 'Green',
        username: 'demo_paige41',
        email: 'demo-demo_paige41@example.com',
        phoneNumber: '+15550000041',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 140,
      },
      {
        firstName: 'Quincy',
        lastName: 'Adams',
        username: 'demo_quincy42',
        email: 'demo-demo_quincy42@example.com',
        phoneNumber: '+15550000042',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 141,
      },
      {
        firstName: 'Rosa',
        lastName: 'Nelson',
        username: 'demo_rosa43',
        email: 'demo-demo_rosa43@example.com',
        phoneNumber: '+15550000043',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 2,
        ip: 142,
      },
      {
        firstName: 'Steve',
        lastName: 'Baker',
        username: 'demo_steve44',
        email: 'demo-demo_steve44@example.com',
        phoneNumber: '+15550000044',
        emailVerified: false,
        phoneNumberVerified: false,
        accessLevel: 0,
        ip: 143,
      },
      {
        firstName: 'Tara',
        lastName: 'Hall',
        username: 'demo_tara45',
        email: 'demo-demo_tara45@example.com',
        phoneNumber: '+15550000045',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 144,
      },
      {
        firstName: 'Ulrich',
        lastName: 'Rivera',
        username: 'demo_ulrich46',
        email: 'demo-demo_ulrich46@example.com',
        phoneNumber: '+15550000046',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 145,
      },
      {
        firstName: 'Vera',
        lastName: 'Campbell',
        username: 'demo_vera47',
        email: 'demo-demo_vera47@example.com',
        phoneNumber: '+15550000047',
        emailVerified: true,
        phoneNumberVerified: false,
        accessLevel: 1,
        ip: 146,
      },
      {
        firstName: 'Walter',
        lastName: 'Mitchell',
        username: 'demo_walter48',
        email: 'demo-demo_walter48@example.com',
        phoneNumber: '+15550000048',
        emailVerified: false,
        phoneNumberVerified: true,
        accessLevel: 2,
        ip: 147,
      },
      {
        firstName: 'Xena',
        lastName: 'Carter',
        username: 'demo_xena49',
        email: 'demo-demo_xena49@example.com',
        phoneNumber: '+15550000049',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 0,
        ip: 148,
      },
      {
        firstName: 'Yusuf',
        lastName: 'Roberts',
        username: 'demo_yusuf50',
        email: 'demo-demo_yusuf50@example.com',
        phoneNumber: '+15550000050',
        emailVerified: true,
        phoneNumberVerified: true,
        accessLevel: 1,
        ip: 149,
      },
    ],
    sessions: [
      // User 0 (Alice)
      {
        userIndex: 0,
        deviceType: 'desktop',
        deviceName: 'MacBook Pro 16"',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.1.100',
        location: 'New York, US',
        twoFactorVerified: true,
      },
      {
        userIndex: 0,
        deviceType: 'mobile',
        deviceName: 'iPhone 15 Pro',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.1.101',
        location: 'New York, US',
        twoFactorVerified: false,
      },
      // User 1 (Bob)
      {
        userIndex: 1,
        deviceType: 'desktop',
        deviceName: 'Windows Desktop',
        browserName: 'Firefox',
        browserVersion: '115.0',
        ipAddress: '192.168.2.50',
        location: 'London, UK',
        twoFactorVerified: true,
      },
      {
        userIndex: 1,
        deviceType: 'mobile',
        deviceName: 'Samsung Galaxy S24',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.2.51',
        location: 'London, UK',
        twoFactorVerified: false,
      },
      // User 2 (Charlie)
      {
        userIndex: 2,
        deviceType: 'tablet',
        deviceName: 'iPad Pro 12.9"',
        browserName: 'Safari',
        browserVersion: '16.0',
        ipAddress: '192.168.3.75',
        location: 'Tokyo, JP',
        twoFactorVerified: false,
      },
      {
        userIndex: 2,
        deviceType: 'desktop',
        deviceName: 'iMac 27"',
        browserName: 'Edge',
        browserVersion: '118.0',
        ipAddress: '192.168.3.76',
        location: 'Tokyo, JP',
        twoFactorVerified: true,
      },
      // User 3 (Diana)
      {
        userIndex: 3,
        deviceType: 'mobile',
        deviceName: 'Pixel 8 Pro',
        browserName: 'Chrome',
        browserVersion: '119.0',
        ipAddress: '192.168.4.25',
        location: 'Paris, FR',
        twoFactorVerified: false,
      },
      // User 4 (Eve)
      {
        userIndex: 4,
        deviceType: 'desktop',
        deviceName: 'Linux Workstation',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.5.10',
        location: 'Sydney, AU',
        twoFactorVerified: true,
      },
      // User 5 (Frank)
      {
        userIndex: 5,
        deviceType: 'desktop',
        deviceName: 'Dell XPS 15',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.6.10',
        location: 'Berlin, DE',
        twoFactorVerified: true,
      },
      {
        userIndex: 5,
        deviceType: 'mobile',
        deviceName: 'iPhone 14',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.6.11',
        location: 'Berlin, DE',
        twoFactorVerified: false,
      },
      // User 6 (Grace)
      {
        userIndex: 6,
        deviceType: 'tablet',
        deviceName: 'iPad Air',
        browserName: 'Safari',
        browserVersion: '16.5',
        ipAddress: '192.168.7.10',
        location: 'Toronto, CA',
        twoFactorVerified: true,
      },
      // User 7 (Henry)
      {
        userIndex: 7,
        deviceType: 'desktop',
        deviceName: 'Mac Mini M2',
        browserName: 'Firefox',
        browserVersion: '121.0',
        ipAddress: '192.168.8.10',
        location: 'Miami, US',
        twoFactorVerified: true,
      },
      {
        userIndex: 7,
        deviceType: 'mobile',
        deviceName: 'OnePlus 12',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.8.11',
        location: 'Miami, US',
        twoFactorVerified: true,
      },
      // User 8 (Ivy)
      {
        userIndex: 8,
        deviceType: 'desktop',
        deviceName: 'HP Spectre',
        browserName: 'Edge',
        browserVersion: '120.0',
        ipAddress: '192.168.9.10',
        location: 'Seoul, KR',
        twoFactorVerified: false,
      },
      // User 9 (Jack)
      {
        userIndex: 9,
        deviceType: 'mobile',
        deviceName: 'iPhone 15',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.10.10',
        location: 'Mexico City, MX',
        twoFactorVerified: true,
      },
      {
        userIndex: 9,
        deviceType: 'desktop',
        deviceName: 'Lenovo ThinkPad',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.10.11',
        location: 'Mexico City, MX',
        twoFactorVerified: true,
      },
      // User 10 (Karen)
      {
        userIndex: 10,
        deviceType: 'desktop',
        deviceName: 'MacBook Air M3',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.11.10',
        location: 'Amsterdam, NL',
        twoFactorVerified: true,
      },
      // User 11 (Leo)
      {
        userIndex: 11,
        deviceType: 'mobile',
        deviceName: 'Samsung Galaxy Z Fold',
        browserName: 'Samsung Internet',
        browserVersion: '23.0',
        ipAddress: '192.168.12.10',
        location: 'Rome, IT',
        twoFactorVerified: false,
      },
      // User 12 (Mia)
      {
        userIndex: 12,
        deviceType: 'desktop',
        deviceName: 'Custom PC Build',
        browserName: 'Brave',
        browserVersion: '1.62',
        ipAddress: '192.168.13.10',
        location: 'Barcelona, ES',
        twoFactorVerified: true,
      },
      {
        userIndex: 12,
        deviceType: 'tablet',
        deviceName: 'Samsung Tab S9',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.13.11',
        location: 'Barcelona, ES',
        twoFactorVerified: true,
      },
      // User 13 (Nathan)
      {
        userIndex: 13,
        deviceType: 'desktop',
        deviceName: 'Surface Pro 9',
        browserName: 'Edge',
        browserVersion: '120.0',
        ipAddress: '192.168.14.10',
        location: 'Chicago, US',
        twoFactorVerified: true,
      },
      // User 14 (Olivia)
      {
        userIndex: 14,
        deviceType: 'mobile',
        deviceName: 'iPhone SE',
        browserName: 'Safari',
        browserVersion: '16.0',
        ipAddress: '192.168.15.10',
        location: 'Vancouver, CA',
        twoFactorVerified: false,
      },
      {
        userIndex: 14,
        deviceType: 'desktop',
        deviceName: 'iMac 24"',
        browserName: 'Chrome',
        browserVersion: '119.0',
        ipAddress: '192.168.15.11',
        location: 'Vancouver, CA',
        twoFactorVerified: true,
      },
      // User 15 (Peter)
      {
        userIndex: 15,
        deviceType: 'desktop',
        deviceName: 'ASUS ROG',
        browserName: 'Opera GX',
        browserVersion: '105.0',
        ipAddress: '192.168.16.10',
        location: 'Stockholm, SE',
        twoFactorVerified: false,
      },
      // User 16 (Quinn)
      {
        userIndex: 16,
        deviceType: 'mobile',
        deviceName: 'Pixel 7',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.17.10',
        location: 'Dublin, IE',
        twoFactorVerified: true,
      },
      // User 17 (Rachel)
      {
        userIndex: 17,
        deviceType: 'desktop',
        deviceName: 'Mac Studio',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.18.10',
        location: 'Los Angeles, US',
        twoFactorVerified: true,
      },
      {
        userIndex: 17,
        deviceType: 'mobile',
        deviceName: 'iPhone 15 Pro Max',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.18.11',
        location: 'Los Angeles, US',
        twoFactorVerified: true,
      },
      {
        userIndex: 17,
        deviceType: 'tablet',
        deviceName: 'iPad Pro 11"',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.18.12',
        location: 'Los Angeles, US',
        twoFactorVerified: false,
      },
      // User 18 (Sam)
      {
        userIndex: 18,
        deviceType: 'desktop',
        deviceName: 'Framework Laptop',
        browserName: 'Firefox',
        browserVersion: '120.0',
        ipAddress: '192.168.19.10',
        location: 'Austin, US',
        twoFactorVerified: true,
      },
      // User 19 (Tina)
      {
        userIndex: 19,
        deviceType: 'mobile',
        deviceName: 'Nothing Phone 2',
        browserName: 'Chrome',
        browserVersion: '119.0',
        ipAddress: '192.168.20.10',
        location: 'Mumbai, IN',
        twoFactorVerified: false,
      },
      // User 20 (Uma)
      {
        userIndex: 20,
        deviceType: 'desktop',
        deviceName: 'Razer Blade',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.21.10',
        location: 'Singapore, SG',
        twoFactorVerified: true,
      },
      // User 21 (Victor)
      {
        userIndex: 21,
        deviceType: 'desktop',
        deviceName: 'HP Omen',
        browserName: 'Firefox',
        browserVersion: '120.0',
        ipAddress: '192.168.22.10',
        location: 'São Paulo, BR',
        twoFactorVerified: true,
      },
      {
        userIndex: 21,
        deviceType: 'mobile',
        deviceName: 'Motorola Edge',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.22.11',
        location: 'São Paulo, BR',
        twoFactorVerified: false,
      },
      // User 22 (Wendy)
      {
        userIndex: 22,
        deviceType: 'tablet',
        deviceName: 'Surface Go 3',
        browserName: 'Edge',
        browserVersion: '120.0',
        ipAddress: '192.168.23.10',
        location: 'Seattle, US',
        twoFactorVerified: true,
      },
      // User 23 (Xavier)
      {
        userIndex: 23,
        deviceType: 'desktop',
        deviceName: 'MSI Creator',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.24.10',
        location: 'Copenhagen, DK',
        twoFactorVerified: false,
      },
      // User 24 (Yara)
      {
        userIndex: 24,
        deviceType: 'mobile',
        deviceName: 'iPhone 14 Pro',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.25.10',
        location: 'Dubai, AE',
        twoFactorVerified: true,
      },
      {
        userIndex: 24,
        deviceType: 'desktop',
        deviceName: 'MacBook Pro 14"',
        browserName: 'Arc',
        browserVersion: '1.20',
        ipAddress: '192.168.25.11',
        location: 'Dubai, AE',
        twoFactorVerified: true,
      },
      // User 25 (Zack)
      {
        userIndex: 25,
        deviceType: 'desktop',
        deviceName: 'Alienware Aurora',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.26.10',
        location: 'Phoenix, US',
        twoFactorVerified: true,
      },
      // User 26 (Amber)
      {
        userIndex: 26,
        deviceType: 'mobile',
        deviceName: 'Samsung Galaxy A54',
        browserName: 'Chrome',
        browserVersion: '119.0',
        ipAddress: '192.168.27.10',
        location: 'Brussels, BE',
        twoFactorVerified: false,
      },
      // User 27 (Brandon)
      {
        userIndex: 27,
        deviceType: 'desktop',
        deviceName: 'Acer Swift',
        browserName: 'Edge',
        browserVersion: '119.0',
        ipAddress: '192.168.28.10',
        location: 'Vienna, AT',
        twoFactorVerified: true,
      },
      // User 28 (Chloe)
      {
        userIndex: 28,
        deviceType: 'tablet',
        deviceName: 'iPad Mini',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.29.10',
        location: 'Zurich, CH',
        twoFactorVerified: true,
      },
      {
        userIndex: 28,
        deviceType: 'desktop',
        deviceName: 'Mac Pro',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.29.11',
        location: 'Zurich, CH',
        twoFactorVerified: true,
      },
      // User 29 (Derek)
      {
        userIndex: 29,
        deviceType: 'desktop',
        deviceName: 'System76 Lemur',
        browserName: 'Firefox',
        browserVersion: '121.0',
        ipAddress: '192.168.30.10',
        location: 'Denver, US',
        twoFactorVerified: true,
      },
      // User 30 (Elena)
      {
        userIndex: 30,
        deviceType: 'mobile',
        deviceName: 'Xiaomi 14',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.31.10',
        location: 'Madrid, ES',
        twoFactorVerified: false,
      },
      // User 31 (Felix)
      {
        userIndex: 31,
        deviceType: 'desktop',
        deviceName: 'Gigabyte Aero',
        browserName: 'Vivaldi',
        browserVersion: '6.5',
        ipAddress: '192.168.32.10',
        location: 'Oslo, NO',
        twoFactorVerified: true,
      },
      // User 32 (Gina)
      {
        userIndex: 32,
        deviceType: 'desktop',
        deviceName: 'MacBook Pro M3',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.33.10',
        location: 'Boston, US',
        twoFactorVerified: true,
      },
      {
        userIndex: 32,
        deviceType: 'mobile',
        deviceName: 'iPhone 15',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.33.11',
        location: 'Boston, US',
        twoFactorVerified: true,
      },
      // User 33 (Hugo)
      {
        userIndex: 33,
        deviceType: 'tablet',
        deviceName: 'Lenovo Tab P12',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.34.10',
        location: 'Lisbon, PT',
        twoFactorVerified: false,
      },
      // User 34 (Iris)
      {
        userIndex: 34,
        deviceType: 'desktop',
        deviceName: 'HP Elite',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.35.10',
        location: 'Helsinki, FI',
        twoFactorVerified: true,
      },
      // User 35 (Jake)
      {
        userIndex: 35,
        deviceType: 'mobile',
        deviceName: 'Google Pixel 8',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.36.10',
        location: 'Portland, US',
        twoFactorVerified: false,
      },
      // User 36 (Kira)
      {
        userIndex: 36,
        deviceType: 'desktop',
        deviceName: 'Dell Precision',
        browserName: 'Firefox',
        browserVersion: '120.0',
        ipAddress: '192.168.37.10',
        location: 'Warsaw, PL',
        twoFactorVerified: true,
      },
      {
        userIndex: 36,
        deviceType: 'mobile',
        deviceName: 'Sony Xperia 1V',
        browserName: 'Chrome',
        browserVersion: '119.0',
        ipAddress: '192.168.37.11',
        location: 'Warsaw, PL',
        twoFactorVerified: false,
      },
      // User 37 (Liam)
      {
        userIndex: 37,
        deviceType: 'desktop',
        deviceName: 'Custom Workstation',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.38.10',
        location: 'San Francisco, US',
        twoFactorVerified: true,
      },
      // User 38 (Maya)
      {
        userIndex: 38,
        deviceType: 'tablet',
        deviceName: 'iPad Pro 12.9" M2',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.39.10',
        location: 'Montreal, CA',
        twoFactorVerified: true,
      },
      // User 39 (Noah)
      {
        userIndex: 39,
        deviceType: 'desktop',
        deviceName: 'ThinkCentre M90',
        browserName: 'Edge',
        browserVersion: '120.0',
        ipAddress: '192.168.40.10',
        location: 'Prague, CZ',
        twoFactorVerified: false,
      },
      // User 40 (Paige)
      {
        userIndex: 40,
        deviceType: 'mobile',
        deviceName: 'iPhone 13',
        browserName: 'Safari',
        browserVersion: '16.0',
        ipAddress: '192.168.41.10',
        location: 'Atlanta, US',
        twoFactorVerified: true,
      },
      {
        userIndex: 40,
        deviceType: 'desktop',
        deviceName: 'iMac M1',
        browserName: 'Safari',
        browserVersion: '16.5',
        ipAddress: '192.168.41.11',
        location: 'Atlanta, US',
        twoFactorVerified: true,
      },
      // User 41 (Quincy)
      {
        userIndex: 41,
        deviceType: 'desktop',
        deviceName: 'Lenovo Legion',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.42.10',
        location: 'Philadelphia, US',
        twoFactorVerified: true,
      },
      // User 42 (Rosa)
      {
        userIndex: 42,
        deviceType: 'mobile',
        deviceName: 'Samsung Galaxy S23',
        browserName: 'Samsung Internet',
        browserVersion: '23.0',
        ipAddress: '192.168.43.10',
        location: 'Buenos Aires, AR',
        twoFactorVerified: true,
      },
      // User 43 (Steve)
      {
        userIndex: 43,
        deviceType: 'desktop',
        deviceName: 'Dell Inspiron',
        browserName: 'Firefox',
        browserVersion: '119.0',
        ipAddress: '192.168.44.10',
        location: 'Nashville, US',
        twoFactorVerified: false,
      },
      // User 44 (Tara)
      {
        userIndex: 44,
        deviceType: 'tablet',
        deviceName: 'Amazon Fire HD',
        browserName: 'Silk',
        browserVersion: '100.0',
        ipAddress: '192.168.45.10',
        location: 'Manchester, UK',
        twoFactorVerified: true,
      },
      {
        userIndex: 44,
        deviceType: 'desktop',
        deviceName: 'HP Pavilion',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.45.11',
        location: 'Manchester, UK',
        twoFactorVerified: true,
      },
      // User 45 (Ulrich)
      {
        userIndex: 45,
        deviceType: 'desktop',
        deviceName: 'Mini PC',
        browserName: 'Firefox',
        browserVersion: '120.0',
        ipAddress: '192.168.46.10',
        location: 'Munich, DE',
        twoFactorVerified: true,
      },
      // User 46 (Vera)
      {
        userIndex: 46,
        deviceType: 'mobile',
        deviceName: 'Oppo Find X6',
        browserName: 'Chrome',
        browserVersion: '119.0',
        ipAddress: '192.168.47.10',
        location: 'Bangkok, TH',
        twoFactorVerified: false,
      },
      // User 47 (Walter)
      {
        userIndex: 47,
        deviceType: 'desktop',
        deviceName: 'HP Z Workstation',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.48.10',
        location: 'Houston, US',
        twoFactorVerified: true,
      },
      {
        userIndex: 47,
        deviceType: 'mobile',
        deviceName: 'iPhone 15 Plus',
        browserName: 'Safari',
        browserVersion: '17.0',
        ipAddress: '192.168.48.11',
        location: 'Houston, US',
        twoFactorVerified: true,
      },
      // User 48 (Xena)
      {
        userIndex: 48,
        deviceType: 'tablet',
        deviceName: 'Galaxy Tab S8',
        browserName: 'Chrome',
        browserVersion: '120.0',
        ipAddress: '192.168.49.10',
        location: 'Auckland, NZ',
        twoFactorVerified: true,
      },
      // User 49 (Yusuf)
      {
        userIndex: 49,
        deviceType: 'desktop',
        deviceName: 'Huawei MateStation',
        browserName: 'Edge',
        browserVersion: '120.0',
        ipAddress: '192.168.50.10',
        location: 'Istanbul, TR',
        twoFactorVerified: true,
      },
    ],
    notifications: [
      // User 0 (Alice)
      {
        userIndex: 0,
        description:
          'Welcome to the platform! Get started by exploring features.',
        icon: 'info',
        type: 'globalGeneral',
        isRead: true,
      },
      {
        userIndex: 0,
        description: 'Your profile has been verified successfully.',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 0,
        description: 'New feature available: Check out the voting system!',
        icon: 'award',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 0,
        description: 'Your favorite artist just released a new track!',
        icon: 'music',
        type: 'userGeneral',
        isRead: false,
      },
      // User 1 (Bob)
      {
        userIndex: 1,
        description: 'Complete your profile to unlock all features.',
        icon: 'user',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 1,
        description: 'System maintenance scheduled for next week.',
        icon: 'warning',
        type: 'globalGeneral',
        isRead: true,
      },
      {
        userIndex: 1,
        description: 'You earned a badge for being an early adopter!',
        icon: 'award',
        type: 'userGeneral',
        isRead: false,
      },
      // User 2 (Charlie)
      {
        userIndex: 2,
        description: 'You have a new follower!',
        icon: 'user',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 2,
        description: 'Your review was helpful to others.',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 2,
        description: 'Weekly chart is now available. Check your rankings!',
        icon: 'chart',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 3 (Diana)
      {
        userIndex: 3,
        description: 'Welcome! Start by adding a payment method.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 3,
        description: 'Security tip: Enable two-factor authentication.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      // User 4 (Eve)
      {
        userIndex: 4,
        description: 'Congratulations on your first vote!',
        icon: 'award',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 4,
        description: 'Check out trending artists this week.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 5 (Frank)
      {
        userIndex: 5,
        description: 'Your subscription is about to renew.',
        icon: 'info',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 5,
        description: 'New collaboration feature is live!',
        icon: 'success',
        type: 'globalGeneral',
        isRead: true,
      },
      {
        userIndex: 5,
        description: 'An artist you follow is nominated for an award!',
        icon: 'award',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 6 (Grace)
      {
        userIndex: 6,
        description: 'Welcome aboard! Explore your dashboard.',
        icon: 'info',
        type: 'globalGeneral',
        isRead: true,
      },
      {
        userIndex: 6,
        description: 'Your account security is strong. Great job!',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      // User 7 (Henry)
      {
        userIndex: 7,
        description: 'You have admin privileges. Use them wisely!',
        icon: 'warning',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 7,
        description: 'New moderation tools available.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 7,
        description: 'Report submitted successfully.',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      // User 8 (Ivy)
      {
        userIndex: 8,
        description: 'Your playlist has been featured!',
        icon: 'award',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 8,
        description: 'Weekly digest: 5 new songs from your favorites.',
        icon: 'music',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 9 (Jack)
      {
        userIndex: 9,
        description: 'Payment method updated successfully.',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 9,
        description: 'Vote for the best newcomer of the month!',
        icon: 'award',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 9,
        description: 'Your review received 10 helpful votes.',
        icon: 'success',
        type: 'userGeneral',
        isRead: false,
      },
      // User 10 (Karen)
      {
        userIndex: 10,
        description:
          'Welcome! Complete your profile for better recommendations.',
        icon: 'info',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 10,
        description: 'New privacy settings available.',
        icon: 'warning',
        type: 'globalGeneral',
        isRead: true,
      },
      // User 11 (Leo)
      {
        userIndex: 11,
        description: 'Your favorite song moved up in the charts!',
        icon: 'chart',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 11,
        description: 'Limited time: Vote for exclusive awards.',
        icon: 'award',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 12 (Mia)
      {
        userIndex: 12,
        description: 'Congratulations! You reached platinum fan status.',
        icon: 'award',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 12,
        description: 'Exclusive content unlocked for platinum fans.',
        icon: 'success',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 12,
        description: 'Admin dashboard has new analytics.',
        icon: 'info',
        type: 'userGeneral',
        isRead: false,
      },
      // User 13 (Nathan)
      {
        userIndex: 13,
        description: 'Your session expired. Please log in again.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 13,
        description: 'New recommendations based on your listening history.',
        icon: 'music',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 14 (Olivia)
      {
        userIndex: 14,
        description: 'Artist verification pending review.',
        icon: 'info',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 14,
        description: 'Community guidelines updated.',
        icon: 'warning',
        type: 'globalGeneral',
        isRead: true,
      },
      {
        userIndex: 14,
        description: 'Your comment was liked by 25 people!',
        icon: 'success',
        type: 'userGeneral',
        isRead: false,
      },
      // User 15 (Peter)
      {
        userIndex: 15,
        description: 'New login detected from Stockholm.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 15,
        description: 'Discover weekly: Fresh picks for you.',
        icon: 'music',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 16 (Quinn)
      {
        userIndex: 16,
        description: 'Your vote was counted successfully.',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 16,
        description: 'Award ceremony livestream starts tomorrow!',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 17 (Rachel)
      {
        userIndex: 17,
        description: 'You have admin access. Review pending content.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 17,
        description: 'Monthly report is ready for review.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 17,
        description: 'User support request assigned to you.',
        icon: 'user',
        type: 'userGeneral',
        isRead: false,
      },
      // User 18 (Sam)
      {
        userIndex: 18,
        description: 'Your feedback helped improve the app!',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 18,
        description: 'Beta features are now available for testing.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 19 (Tina)
      {
        userIndex: 19,
        description: 'Verify your phone number to secure your account.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 19,
        description: 'Trending now: Top 10 songs of the week.',
        icon: 'chart',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 20 (Uma)
      {
        userIndex: 20,
        description: 'Your playlist reached 1,000 followers!',
        icon: 'award',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 20,
        description: 'New sharing options available.',
        icon: 'info',
        type: 'globalGeneral',
        isRead: true,
      },
      // User 21 (Victor)
      {
        userIndex: 21,
        description: 'Artist you follow went live!',
        icon: 'music',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 21,
        description: 'Your account anniversary is coming up!',
        icon: 'award',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 21,
        description: 'Special offer: Premium upgrade discount.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 22 (Wendy)
      {
        userIndex: 22,
        description: 'Admin tools refreshed. Check whats new.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 22,
        description: 'Content moderation queue has 5 items.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      // User 23 (Xavier)
      {
        userIndex: 23,
        description: 'Your email is not verified. Verify now.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 23,
        description: 'New artists matching your taste joined!',
        icon: 'user',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 24 (Yara)
      {
        userIndex: 24,
        description: 'Congratulations on 100 votes cast!',
        icon: 'award',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 24,
        description: 'Your favorite category is trending.',
        icon: 'chart',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 24,
        description: 'Exclusive interview with top artist available.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 25 (Zack)
      {
        userIndex: 25,
        description: 'Welcome to the community!',
        icon: 'info',
        type: 'globalGeneral',
        isRead: true,
      },
      {
        userIndex: 25,
        description: 'Set up your profile to get personalized content.',
        icon: 'user',
        type: 'userGeneral',
        isRead: false,
      },
      // User 26 (Amber)
      {
        userIndex: 26,
        description: 'Your phone verification is pending.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 26,
        description: 'New music from followed artists this week.',
        icon: 'music',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 27 (Brandon)
      {
        userIndex: 27,
        description: 'Admin privileges granted successfully.',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 27,
        description: 'Review the latest user reports.',
        icon: 'warning',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 27,
        description: 'System update completed.',
        icon: 'info',
        type: 'globalGeneral',
        isRead: true,
      },
      // User 28 (Chloe)
      {
        userIndex: 28,
        description: 'Your review was featured on the homepage!',
        icon: 'award',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 28,
        description: 'Connect with other fans in discussions.',
        icon: 'user',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 29 (Derek)
      {
        userIndex: 29,
        description: 'Voting closes in 24 hours. Cast your vote!',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 29,
        description: 'Artist spotlight: Discover rising stars.',
        icon: 'music',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 30 (Elena)
      {
        userIndex: 30,
        description: 'Your phone number is now verified.',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 30,
        description: 'Recommended for you: New genre picks.',
        icon: 'music',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 31 (Felix)
      {
        userIndex: 31,
        description: 'Your session from Oslo is active.',
        icon: 'info',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 31,
        description: 'Artist collaboration feature is live!',
        icon: 'success',
        type: 'globalGeneral',
        isRead: true,
      },
      // User 32 (Gina)
      {
        userIndex: 32,
        description: 'Welcome back! Check whats new.',
        icon: 'info',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 32,
        description: 'Admin dashboard updated with new charts.',
        icon: 'chart',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 32,
        description: 'Pending review items: 12',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      // User 33 (Hugo)
      {
        userIndex: 33,
        description: 'Your favorite song hit #1 on the charts!',
        icon: 'award',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 33,
        description: 'Share your success with friends.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 34 (Iris)
      {
        userIndex: 34,
        description: 'Complete your 2FA setup for extra security.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 34,
        description: 'New releases from your top artists.',
        icon: 'music',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 35 (Jake)
      {
        userIndex: 35,
        description: 'Verify your email to continue.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 35,
        description: 'Join the discussion about latest trends.',
        icon: 'user',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 36 (Kira)
      {
        userIndex: 36,
        description: 'Your vote streak is 7 days!',
        icon: 'award',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 36,
        description: 'Keep voting to maintain your streak.',
        icon: 'info',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 36,
        description: 'Special badge unlocked for consistent voting.',
        icon: 'award',
        type: 'userGeneral',
        isRead: false,
      },
      // User 37 (Liam)
      {
        userIndex: 37,
        description: 'Admin tools available in your dashboard.',
        icon: 'info',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 37,
        description: 'User feedback report is ready.',
        icon: 'chart',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 38 (Maya)
      {
        userIndex: 38,
        description: 'Your recommendations are updated.',
        icon: 'music',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 38,
        description: 'Explore new artists similar to your favorites.',
        icon: 'user',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 39 (Noah)
      {
        userIndex: 39,
        description: 'Security alert: New device logged in.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 39,
        description: 'If this wasnt you, secure your account now.',
        icon: 'warning',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 40 (Paige)
      {
        userIndex: 40,
        description: 'Your feedback is valuable! Take our survey.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 40,
        description: 'Weekly summary: Your activity at a glance.',
        icon: 'chart',
        type: 'userGeneral',
        isRead: true,
      },
      // User 41 (Quincy)
      {
        userIndex: 41,
        description: 'New podcast episode from followed creator.',
        icon: 'music',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 41,
        description: 'Rate your experience with the new feature.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 42 (Rosa)
      {
        userIndex: 42,
        description: 'Admin review completed successfully.',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 42,
        description: 'New moderation guidelines released.',
        icon: 'warning',
        type: 'globalGeneral',
        isRead: true,
      },
      {
        userIndex: 42,
        description: 'Check the updated community rules.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 43 (Steve)
      {
        userIndex: 43,
        description: 'Your account needs attention.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 43,
        description: 'Update your email to continue receiving updates.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 44 (Tara)
      {
        userIndex: 44,
        description: 'Congratulations on 50 helpful reviews!',
        icon: 'award',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 44,
        description: 'Your contribution badge is upgraded.',
        icon: 'award',
        type: 'userGeneral',
        isRead: false,
      },
      // User 45 (Ulrich)
      {
        userIndex: 45,
        description: 'New features in your area are available.',
        icon: 'info',
        type: 'globalGeneral',
        isRead: true,
      },
      {
        userIndex: 45,
        description: 'Local artists spotlight this week.',
        icon: 'music',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 46 (Vera)
      {
        userIndex: 46,
        description: 'Your phone verification expired.',
        icon: 'warning',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 46,
        description: 'Reverify to maintain full access.',
        icon: 'info',
        type: 'withButtonLink',
        isRead: false,
      },
      // User 47 (Walter)
      {
        userIndex: 47,
        description: 'Admin status confirmed. Welcome to the team!',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      {
        userIndex: 47,
        description: 'Moderation queue awaiting review.',
        icon: 'warning',
        type: 'withButtonLink',
        isRead: false,
      },
      {
        userIndex: 47,
        description: 'Team sync scheduled for this week.',
        icon: 'info',
        type: 'userGeneral',
        isRead: false,
      },
      // User 48 (Xena)
      {
        userIndex: 48,
        description: 'Your playlist was shared by 10 users!',
        icon: 'award',
        type: 'userGeneral',
        isRead: false,
      },
      {
        userIndex: 48,
        description: 'Growing community engagement noted.',
        icon: 'success',
        type: 'userGeneral',
        isRead: true,
      },
      // User 49 (Yusuf)
      {
        userIndex: 49,
        description: 'Welcome! Start exploring trending content.',
        icon: 'info',
        type: 'globalGeneral',
        isRead: true,
      },
      {
        userIndex: 49,
        description: 'Connect your social accounts for more features.',
        icon: 'user',
        type: 'withButtonLink',
        isRead: false,
      },
    ],
    reviews: [
      {
        reviewerIndex: 0,
        targetIndex: 1,
        rating: '5',
        comment: 'Excellent artist with amazing work!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 0,
        targetIndex: 5,
        rating: '4',
        comment: 'Great music, very talented!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 0,
        targetIndex: 12,
        rating: '5',
        comment: 'Incredible vocal range and stage presence.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 1,
        targetIndex: 2,
        rating: '4',
        comment: 'Great collaboration experience.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 1,
        targetIndex: 7,
        rating: '3',
        comment: 'Good artist, room for improvement.',
        recommended: 'maybe',
      },
      {
        reviewerIndex: 2,
        targetIndex: 0,
        rating: '5',
        comment: 'Highly professional and talented.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 2,
        targetIndex: 8,
        rating: '4',
        comment: 'Love the unique sound and style.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 3,
        targetIndex: 4,
        rating: '5',
        comment: 'Best live performance I have seen!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 3,
        targetIndex: 9,
        rating: '4',
        comment: 'Innovative approach to music.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 4,
        targetIndex: 3,
        rating: '3',
        comment: 'Decent work, expected more.',
        recommended: 'maybe',
      },
      {
        reviewerIndex: 5,
        targetIndex: 6,
        rating: '5',
        comment: 'Fantastic producer with great beats.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 5,
        targetIndex: 10,
        rating: '4',
        comment: 'Solid performer with good energy.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 6,
        targetIndex: 5,
        rating: '4',
        comment: 'Enjoyed the collaboration.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 7,
        targetIndex: 11,
        rating: '5',
        comment: 'Absolute legend in the industry!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 7,
        targetIndex: 0,
        rating: '4',
        comment: 'Always delivers quality work.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 8,
        targetIndex: 13,
        rating: '4',
        comment: 'Great stage presence and charisma.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 9,
        targetIndex: 14,
        rating: '5',
        comment: 'One of the best new artists!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 10,
        targetIndex: 15,
        rating: '3',
        comment: 'Good potential, needs more experience.',
        recommended: 'maybe',
      },
      {
        reviewerIndex: 11,
        targetIndex: 16,
        rating: '4',
        comment: 'Impressive songwriting skills.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 12,
        targetIndex: 17,
        rating: '5',
        comment: 'World-class talent!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 13,
        targetIndex: 18,
        rating: '4',
        comment: 'Consistent quality in every release.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 14,
        targetIndex: 19,
        rating: '2',
        comment: 'Not my style, but technically skilled.',
        recommended: 'no',
      },
      {
        reviewerIndex: 15,
        targetIndex: 20,
        rating: '5',
        comment: 'Mind-blowing performance!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 16,
        targetIndex: 21,
        rating: '4',
        comment: 'Great energy and connection with fans.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 17,
        targetIndex: 22,
        rating: '5',
        comment: 'Exceptional in every way.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 18,
        targetIndex: 23,
        rating: '3',
        comment: 'Average performance, expected better.',
        recommended: 'maybe',
      },
      {
        reviewerIndex: 19,
        targetIndex: 24,
        rating: '4',
        comment: 'Really enjoyed the latest album.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 20,
        targetIndex: 25,
        rating: '5',
        comment: 'Pure talent and dedication.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 21,
        targetIndex: 26,
        rating: '4',
        comment: 'Great work ethic and results.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 22,
        targetIndex: 27,
        rating: '5',
        comment: 'Admin-certified excellence!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 23,
        targetIndex: 28,
        rating: '3',
        comment: 'Decent but could improve mixing.',
        recommended: 'maybe',
      },
      {
        reviewerIndex: 24,
        targetIndex: 29,
        rating: '4',
        comment: 'Solid performances consistently.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 25,
        targetIndex: 30,
        rating: '5',
        comment: 'Rising star to watch!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 26,
        targetIndex: 31,
        rating: '4',
        comment: 'Unique style and sound.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 27,
        targetIndex: 32,
        rating: '5',
        comment: 'Professional and talented admin.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 28,
        targetIndex: 33,
        rating: '4',
        comment: 'Great artistic vision.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 29,
        targetIndex: 34,
        rating: '4',
        comment: 'Love the experimental approach.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 30,
        targetIndex: 35,
        rating: '3',
        comment: 'Needs more original content.',
        recommended: 'maybe',
      },
      {
        reviewerIndex: 31,
        targetIndex: 36,
        rating: '5',
        comment: 'Incredible vocal control!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 32,
        targetIndex: 37,
        rating: '5',
        comment: 'True artist and visionary.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 33,
        targetIndex: 38,
        rating: '4',
        comment: 'Enjoyed every track.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 34,
        targetIndex: 39,
        rating: '3',
        comment: 'Good but not groundbreaking.',
        recommended: 'maybe',
      },
      {
        reviewerIndex: 35,
        targetIndex: 40,
        rating: '4',
        comment: 'Catchy tunes and great hooks.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 36,
        targetIndex: 41,
        rating: '5',
        comment: 'Future superstar material!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 37,
        targetIndex: 42,
        rating: '4',
        comment: 'Strong debut showing.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 38,
        targetIndex: 43,
        rating: '2',
        comment: 'Needs significant improvement.',
        recommended: 'no',
      },
      {
        reviewerIndex: 39,
        targetIndex: 44,
        rating: '5',
        comment: 'Absolutely fantastic!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 40,
        targetIndex: 45,
        rating: '4',
        comment: 'Solid work across the board.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 41,
        targetIndex: 46,
        rating: '4',
        comment: 'Great international appeal.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 42,
        targetIndex: 47,
        rating: '5',
        comment: 'Admin excellence recognized!',
        recommended: 'yes',
      },
      {
        reviewerIndex: 43,
        targetIndex: 48,
        rating: '3',
        comment: 'Shows promise for the future.',
        recommended: 'maybe',
      },
      {
        reviewerIndex: 44,
        targetIndex: 49,
        rating: '4',
        comment: 'Impressive cultural fusion.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 45,
        targetIndex: 0,
        rating: '5',
        comment: 'Timeless quality work.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 46,
        targetIndex: 1,
        rating: '4',
        comment: 'Reliable and consistent artist.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 47,
        targetIndex: 2,
        rating: '5',
        comment: 'Top-tier professional.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 48,
        targetIndex: 3,
        rating: '4',
        comment: 'Great collaborative spirit.',
        recommended: 'yes',
      },
      {
        reviewerIndex: 49,
        targetIndex: 4,
        rating: '5',
        comment: 'Outstanding in every aspect!',
        recommended: 'yes',
      },
    ],
    paymentMethods: [
      {
        userIndex: 0,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 4242',
        expiryDate: '12/27',
      },
      {
        userIndex: 1,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 5555',
        expiryDate: '06/26',
      },
      {
        userIndex: 2,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 1234',
        expiryDate: '03/28',
      },
      {
        userIndex: 5,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 7890',
        expiryDate: '09/26',
      },
      {
        userIndex: 6,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 3456',
        expiryDate: '01/27',
      },
      {
        userIndex: 7,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 6789',
        expiryDate: '11/28',
      },
      {
        userIndex: 8,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 2345',
        expiryDate: '05/26',
      },
      {
        userIndex: 9,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 8901',
        expiryDate: '08/27',
      },
      {
        userIndex: 10,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 4567',
        expiryDate: '02/28',
      },
      {
        userIndex: 12,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 0123',
        expiryDate: '07/26',
      },
      {
        userIndex: 13,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 5678',
        expiryDate: '10/27',
      },
      {
        userIndex: 14,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 9012',
        expiryDate: '04/28',
      },
      {
        userIndex: 17,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 3457',
        expiryDate: '12/26',
      },
      {
        userIndex: 18,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 7891',
        expiryDate: '06/27',
      },
      {
        userIndex: 20,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 2346',
        expiryDate: '03/28',
      },
      {
        userIndex: 21,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 6780',
        expiryDate: '09/26',
      },
      {
        userIndex: 22,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 1235',
        expiryDate: '01/27',
      },
      {
        userIndex: 24,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 5679',
        expiryDate: '11/28',
      },
      {
        userIndex: 25,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 9013',
        expiryDate: '05/26',
      },
      {
        userIndex: 27,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 4568',
        expiryDate: '08/27',
      },
      {
        userIndex: 28,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 8902',
        expiryDate: '02/28',
      },
      {
        userIndex: 29,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 3458',
        expiryDate: '07/26',
      },
      {
        userIndex: 32,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 7892',
        expiryDate: '10/27',
      },
      {
        userIndex: 33,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 2347',
        expiryDate: '04/28',
      },
      {
        userIndex: 36,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 6781',
        expiryDate: '12/26',
      },
      {
        userIndex: 37,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 1236',
        expiryDate: '06/27',
      },
      {
        userIndex: 38,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 5670',
        expiryDate: '03/28',
      },
      {
        userIndex: 40,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 9014',
        expiryDate: '09/26',
      },
      {
        userIndex: 42,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 4569',
        expiryDate: '01/27',
      },
      {
        userIndex: 44,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 8903',
        expiryDate: '11/28',
      },
      {
        userIndex: 45,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 3459',
        expiryDate: '05/26',
      },
      {
        userIndex: 47,
        provider: 'peyapeya',
        type: 'card',
        maskedNumber: '**** **** **** 7893',
        expiryDate: '08/27',
      },
      {
        userIndex: 49,
        provider: 'stripe',
        type: 'card',
        maskedNumber: '**** **** **** 2348',
        expiryDate: '02/28',
      },
    ],
    votes: [
      {
        userIndex: 0,
        nomineeId: nomineeIds[0],
        titleId: titleIds[0],
        categoryId: categoryIds[0],
      },
      {
        userIndex: 0,
        nomineeId: nomineeIds[3],
        titleId: titleIds[2],
        categoryId: categoryIds[3],
      },
      {
        userIndex: 1,
        nomineeId: nomineeIds[1],
        titleId: titleIds[1],
        categoryId: categoryIds[1],
      },
      {
        userIndex: 1,
        nomineeId: nomineeIds[5],
        titleId: titleIds[4],
        categoryId: categoryIds[5],
      },
      {
        userIndex: 2,
        nomineeId: nomineeIds[2],
        titleId: titleIds[2],
        categoryId: categoryIds[2],
      },
      {
        userIndex: 2,
        nomineeId: nomineeIds[7],
        titleId: titleIds[6],
        categoryId: categoryIds[7],
      },
      {
        userIndex: 3,
        nomineeId: nomineeIds[0],
        titleId: titleIds[0],
        categoryId: categoryIds[0],
      },
      {
        userIndex: 3,
        nomineeId: nomineeIds[4],
        titleId: titleIds[3],
        categoryId: categoryIds[4],
      },
      {
        userIndex: 4,
        nomineeId: nomineeIds[1],
        titleId: titleIds[1],
        categoryId: categoryIds[1],
      },
      {
        userIndex: 5,
        nomineeId: nomineeIds[2],
        titleId: titleIds[2],
        categoryId: categoryIds[2],
      },
      {
        userIndex: 5,
        nomineeId: nomineeIds[6],
        titleId: titleIds[5],
        categoryId: categoryIds[6],
      },
      {
        userIndex: 6,
        nomineeId: nomineeIds[3],
        titleId: titleIds[3],
        categoryId: categoryIds[3],
      },
      {
        userIndex: 7,
        nomineeId: nomineeIds[4],
        titleId: titleIds[4],
        categoryId: categoryIds[4],
      },
      {
        userIndex: 7,
        nomineeId: nomineeIds[8],
        titleId: titleIds[7],
        categoryId: categoryIds[8],
      },
      {
        userIndex: 8,
        nomineeId: nomineeIds[0],
        titleId: titleIds[0],
        categoryId: categoryIds[0],
      },
      {
        userIndex: 9,
        nomineeId: nomineeIds[5],
        titleId: titleIds[5],
        categoryId: categoryIds[5],
      },
      {
        userIndex: 9,
        nomineeId: nomineeIds[9],
        titleId: titleIds[9],
        categoryId: categoryIds[9],
      },
      {
        userIndex: 10,
        nomineeId: nomineeIds[1],
        titleId: titleIds[1],
        categoryId: categoryIds[1],
      },
      {
        userIndex: 11,
        nomineeId: nomineeIds[6],
        titleId: titleIds[6],
        categoryId: categoryIds[6],
      },
      {
        userIndex: 12,
        nomineeId: nomineeIds[2],
        titleId: titleIds[2],
        categoryId: categoryIds[2],
      },
      {
        userIndex: 12,
        nomineeId: nomineeIds[7],
        titleId: titleIds[7],
        categoryId: categoryIds[7],
      },
      {
        userIndex: 13,
        nomineeId: nomineeIds[3],
        titleId: titleIds[3],
        categoryId: categoryIds[3],
      },
      {
        userIndex: 14,
        nomineeId: nomineeIds[8],
        titleId: titleIds[8],
        categoryId: categoryIds[8],
      },
      {
        userIndex: 15,
        nomineeId: nomineeIds[4],
        titleId: titleIds[4],
        categoryId: categoryIds[4],
      },
      {
        userIndex: 16,
        nomineeId: nomineeIds[0],
        titleId: titleIds[0],
        categoryId: categoryIds[0],
      },
      {
        userIndex: 16,
        nomineeId: nomineeIds[9],
        titleId: titleIds[9],
        categoryId: categoryIds[9],
      },
      {
        userIndex: 17,
        nomineeId: nomineeIds[5],
        titleId: titleIds[5],
        categoryId: categoryIds[5],
      },
      {
        userIndex: 18,
        nomineeId: nomineeIds[1],
        titleId: titleIds[1],
        categoryId: categoryIds[1],
      },
      {
        userIndex: 19,
        nomineeId: nomineeIds[6],
        titleId: titleIds[6],
        categoryId: categoryIds[6],
      },
      {
        userIndex: 20,
        nomineeId: nomineeIds[2],
        titleId: titleIds[2],
        categoryId: categoryIds[2],
      },
      {
        userIndex: 21,
        nomineeId: nomineeIds[7],
        titleId: titleIds[7],
        categoryId: categoryIds[7],
      },
      {
        userIndex: 22,
        nomineeId: nomineeIds[3],
        titleId: titleIds[3],
        categoryId: categoryIds[3],
      },
      {
        userIndex: 22,
        nomineeId: nomineeIds[8],
        titleId: titleIds[8],
        categoryId: categoryIds[8],
      },
      {
        userIndex: 23,
        nomineeId: nomineeIds[4],
        titleId: titleIds[4],
        categoryId: categoryIds[4],
      },
      {
        userIndex: 24,
        nomineeId: nomineeIds[0],
        titleId: titleIds[0],
        categoryId: categoryIds[0],
      },
      {
        userIndex: 24,
        nomineeId: nomineeIds[9],
        titleId: titleIds[9],
        categoryId: categoryIds[9],
      },
      {
        userIndex: 25,
        nomineeId: nomineeIds[5],
        titleId: titleIds[5],
        categoryId: categoryIds[5],
      },
      {
        userIndex: 26,
        nomineeId: nomineeIds[1],
        titleId: titleIds[1],
        categoryId: categoryIds[1],
      },
      {
        userIndex: 27,
        nomineeId: nomineeIds[6],
        titleId: titleIds[6],
        categoryId: categoryIds[6],
      },
      {
        userIndex: 27,
        nomineeId: nomineeIds[2],
        titleId: titleIds[2],
        categoryId: categoryIds[2],
      },
      {
        userIndex: 28,
        nomineeId: nomineeIds[7],
        titleId: titleIds[7],
        categoryId: categoryIds[7],
      },
      {
        userIndex: 29,
        nomineeId: nomineeIds[3],
        titleId: titleIds[3],
        categoryId: categoryIds[3],
      },
      {
        userIndex: 30,
        nomineeId: nomineeIds[8],
        titleId: titleIds[8],
        categoryId: categoryIds[8],
      },
      {
        userIndex: 31,
        nomineeId: nomineeIds[4],
        titleId: titleIds[4],
        categoryId: categoryIds[4],
      },
      {
        userIndex: 32,
        nomineeId: nomineeIds[0],
        titleId: titleIds[0],
        categoryId: categoryIds[0],
      },
      {
        userIndex: 32,
        nomineeId: nomineeIds[9],
        titleId: titleIds[9],
        categoryId: categoryIds[9],
      },
      {
        userIndex: 33,
        nomineeId: nomineeIds[5],
        titleId: titleIds[5],
        categoryId: categoryIds[5],
      },
      {
        userIndex: 34,
        nomineeId: nomineeIds[1],
        titleId: titleIds[1],
        categoryId: categoryIds[1],
      },
      {
        userIndex: 35,
        nomineeId: nomineeIds[6],
        titleId: titleIds[6],
        categoryId: categoryIds[6],
      },
      {
        userIndex: 36,
        nomineeId: nomineeIds[2],
        titleId: titleIds[2],
        categoryId: categoryIds[2],
      },
      {
        userIndex: 37,
        nomineeId: nomineeIds[7],
        titleId: titleIds[7],
        categoryId: categoryIds[7],
      },
      {
        userIndex: 37,
        nomineeId: nomineeIds[3],
        titleId: titleIds[3],
        categoryId: categoryIds[3],
      },
      {
        userIndex: 38,
        nomineeId: nomineeIds[8],
        titleId: titleIds[8],
        categoryId: categoryIds[8],
      },
      {
        userIndex: 39,
        nomineeId: nomineeIds[4],
        titleId: titleIds[4],
        categoryId: categoryIds[4],
      },
      {
        userIndex: 40,
        nomineeId: nomineeIds[0],
        titleId: titleIds[0],
        categoryId: categoryIds[0],
      },
      {
        userIndex: 41,
        nomineeId: nomineeIds[9],
        titleId: titleIds[9],
        categoryId: categoryIds[9],
      },
      {
        userIndex: 42,
        nomineeId: nomineeIds[5],
        titleId: titleIds[5],
        categoryId: categoryIds[5],
      },
      {
        userIndex: 42,
        nomineeId: nomineeIds[1],
        titleId: titleIds[1],
        categoryId: categoryIds[1],
      },
      {
        userIndex: 43,
        nomineeId: nomineeIds[6],
        titleId: titleIds[6],
        categoryId: categoryIds[6],
      },
      {
        userIndex: 44,
        nomineeId: nomineeIds[2],
        titleId: titleIds[2],
        categoryId: categoryIds[2],
      },
      {
        userIndex: 45,
        nomineeId: nomineeIds[7],
        titleId: titleIds[7],
        categoryId: categoryIds[7],
      },
      {
        userIndex: 46,
        nomineeId: nomineeIds[3],
        titleId: titleIds[3],
        categoryId: categoryIds[3],
      },
      {
        userIndex: 47,
        nomineeId: nomineeIds[8],
        titleId: titleIds[8],
        categoryId: categoryIds[8],
      },
      {
        userIndex: 47,
        nomineeId: nomineeIds[4],
        titleId: titleIds[4],
        categoryId: categoryIds[4],
      },
      {
        userIndex: 48,
        nomineeId: nomineeIds[0],
        titleId: titleIds[0],
        categoryId: categoryIds[0],
      },
      {
        userIndex: 49,
        nomineeId: nomineeIds[9],
        titleId: titleIds[9],
        categoryId: categoryIds[9],
      },
      {
        userIndex: 49,
        nomineeId: nomineeIds[5],
        titleId: titleIds[5],
        categoryId: categoryIds[5],
      },
    ],
  };
}
