export const schools = [
  {
    id: 1,
    name: 'John Cowie Primary School',
    level: 'primary-education',
    type: 'Mixed Boarding',
    location: 'Rusape',
    province: 'Manicaland',
    fees: 350,
    rating: 4.8,
    passRate: 96,
    church: null,
    contacts: [
      { name: 'Econet Number', phone: '+263774531257', role: 'Phone Number' },
      {
        name: 'Netone Number',
        phone: '+263712759124',
        role: 'Phone Number',
      },
    ],
  },
  {
    id: 2,
    name: 'Nyanga High Marist Brothers',
    level: 'o-level-education',
    type: 'Boys Boarding',
    location: 'Nyanga',
    province: 'Manicaland',
    fees: 450,
    rating: 4.5,
    passRate: 98.9,
    church: 'Catholic',
    contacts: [
      { name: 'School Admin', phone: '+263298738', role: 'LandLine Number' },
    ],
  },
  {
    id: 3,
    name: "St Faith's High School",
    level: 'a-level-education',
    type: 'Boys Boarding',
    location: 'Rusape',
    province: 'Manicaland',
    fees: 600,
    rating: 4.7,
    passRate: 99.1,
    church: 'Anglican',
    contacts: [
      { name: 'School Admin', phone: '+263253732', role: 'Landline Number' },
    ],
  },
  {
    id: 4,
    name: 'University of Zimbabwe',
    level: 'tertiary-education',
    type: 'Public',
    province: 'Harare',
    location: 'Harare',
    fees: 600,
    rating: 4.7,
    employmentRate: 49,
    church: null,
  },
];
